### ISSUE TITLE
[api] Endpoint to extract timeseries measurements

### ISSUE THREAD

**Issue by adamscarberry** [USACE/water#15]
- [x] Database sql (or view if required)
- [x] API endpoint /watersheds/:watershed_slug/extract?start=2020-01-01&end=2020-03-01 (streaming JSON: https://echo.labstack.com/cookbook/streaming-response/) will return all configured sites/parameters for a requested watershed (config table: `watershed_usgs_sites`)
- [x] Regression test coverage
- [x] API Docs

**Comment by jeffsuperglide** [comment]
USACE/water-api/pull/71 closes USACE/water/issues/15
