### ISSUE TITLE
Dam Profile Chart Endpoint API Enhancements & Database Migrations

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/water#38]

**Comment by adamscarberry** [comment]
Based on initial discussions, here are the new tables (so far):

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/46494851/189190977-ed2663d2-f4e7-4176-ab9b-d8c2f4e8928b.png">

**Comment by adamscarberry** [comment]
@brettpalmberg WIP here: https://github.com/USACE/water-api/tree/feature/38-dam-profile-chart-endpoint-and-db-migrations

**Comment by adamscarberry** [comment]
@brettpalmberg 
proposed payload for latest timeseries:

```
[
    {
        "datasource_type": "cwms-timeseries",
        "key": "AlumCr-Outflow.Stage.Inst.15Minutes.0.OBS",
        "latest_time": "2022-09-12T20:10:00-00:00",
        "latest_value": 123.99
        
    },
    {
        "datasource_type": "cwms-timeseries",
        "key": "Bluestone-Lake.Elev.Inst.15Minutes.0.OBS",
        "latest_time": "2022-09-12T21:00:00-00:00",
        "latest_value": 456.99
        
    }
]
```

or we could just accept times and values as arrays:

```
[
    {
        "datasource_type": "cwms-timeseries",
        "key": "AlumCr-Outflow.Stage.Inst.15Minutes.0.OBS",
        "times": ["2022-09-12T20:10:00-00:00"]
        "values": [123.99]
        
    },
    {
        "datasource_type": "cwms-timeseries",
        "key": "Bluestone-Lake.Elev.Inst.15Minutes.0.OBS",
        "times": ["2022-09-12T21:00:00-00:00"]
        "values": [456.99]
        
    }
]
```

**Comment by brettpalmberg** [comment]
Thanks @adamscarberry. I like it, I would vote for the second alternative. Will a provider key/value such as `"provider": "USACE-LRH"` or `"provider":"LRH"` be necessary?

**Comment by adamscarberry** [comment]
revised.

Here's the **CreateOrUpdateTimeseries** payload:

```
[
    {
        "datasource_type": "cwms-timeseries",
        "key": "TestLocation-Outflow.Stage.Inst.15Minutes.0.OBS",
        "provider": "LRH",
        "times": ["2022-09-12T20:15:00-00:00", "2022-09-12T20:30:00-00:00"],
        "values": [123.99, 124.10]
        
    },
    {
        "datasource_type": "cwms-timeseries",
        "key": "TestLocation-Lake.Elev.Inst.15Minutes.0.OBS",
        "provider": "LRH",
        "times": ["2022-09-12T21:00:00-00:00", "2022-09-12T21:15:00-00:00"],
        "values": [456.99, 457.20]
        
    }
]
```

Here's the GET payload for **{{base_url}}/timeseries?provider=lrh&datasource_type=cwms-timeseries**:

```
[
    {
        "provider": "lrh",
        "datasource_type": "cwms-timeseries",
        "key": "AlumCr-Lake.Elev.Inst.15Minutes.0.OBS",
        "times": [
            "2022-09-08T16:00:00-04:00"
        ],
        "values": [
            888.22
        ]
    },
    {
        "provider": "lrh",
        "datasource_type": "cwms-timeseries",
        "key": "AlumCr-Lake.Flow.Inst.15Minutes.0.OBS",
        "times": [
            "2022-09-08T16:00:00-04:00"
        ],
        "values": [
            19.28
        ]
    },
    {
        "provider": "lrh",
        "datasource_type": "cwms-timeseries",
        "key": "AlumCr-Outflow.Flow.Inst.15Minutes.0.OBS",
        "times": [
            "2022-09-08T16:00:00-04:00"
        ],
        "values": [
            12.28
        ]
    },
    {
        "provider": "lrh",
        "datasource_type": "cwms-timeseries",
        "key": "TestLocation-Lake.Elev.Inst.15Minutes.0.OBS",
        "times": [
            "2022-09-12T17:15:00-04:00"
        ],
        "values": [
            457.2
        ]
    },
    {
        "provider": "lrh",
        "datasource_type": "cwms-timeseries",
        "key": "TestLocation-Outflow.Stage.Inst.15Minutes.0.OBS",
        "times": [
            "2022-09-12T16:30:00-04:00"
        ],
        "values": [
            124.1
        ]
    }
]
```

**Comment by adamscarberry** [comment]
@brettpalmberg 

Currently, here's the current payload example for creating a visualization mapping:

**POST {{base_url}}/visualizations/{{new_visualization_slug}}/assign**

```
[
    {
        "variable": "pool",
        "key": "TestLocation-Lake.Elev.Inst.15Minutes.0.OBS",
        "datasource_type": "cwms-timeseries"
    },
    {
        "variable": "outflow",
        "key": "TestLocation-Outflow.Stage.Inst.15Minutes.0.OBS",
        "datasource_type": "cwms-timeseries"
    }
]   
```

If I understand correctly, this will be used by the front end UI to assign tsids to a newly created visualization (newly created slug in url param).

❓ I'm thinking we should put the office context in the url for permission check.  Do you agree?

The only office/provider context we have on a visualization is the location_slug (which will lookup the location in the location table and have an attached office/provider)

**POST {{base_url}}/visualizations**

```
{
    "location_slug": "lrh-test-project",
    "name": "LRHTestProject Dam Profile Chart",
    "type_id": "53da77d0-6550-4f02-abf8-4bcd1a596a7c"
}   
```

❓ Perhaps this visualization creation should also have office/provider in the url?

**Comment by brettpalmberg** [comment]
@adamscarberry, I think I agree. Good work thinking through this.

> ❓ I'm thinking we should put the office context in the url for permission check. Do you agree?

Agreed

> ❓ Perhaps this visualization creation should also have office/provider in the url?

Agreed

**Comment by brettpalmberg** [comment]
Work complete; Functional tests of the API are included in the Postman tests included in the repository https://github.com/USACE/water-api.

> Note: Some of the payloads and URL structure we landed on in the end are different than what's shown in earlier discussion here.
