### ISSUE TITLE
[Task]: Manually Sync Watershed/Site/Parameters from Develop to Stable

### ISSUE THREAD

**Issue by adamscarberry** [USACE/water#45]
Transfer over the "subscribed" USGS sites for certain watersheds.

Data acquisition has been occurring in develop based on scripted "subscriptions" for a while.  This needs to be transferred to stable, but it's complicated to replay those actions.

Suggestion emptying the following tables in Stable and manually exporting/importing data from Develop:

1. usgs_site
2. usgs_site_parameters
3. watershed_usgs_sites

This will allow airflow to start acquisition and enable the `extract` endpoints for Stable.

❓ Should I also copy over usgs_measurements or just start from now with airflow?

cc @brettpalmberg

**Comment by adamscarberry** [comment]
<img width="616" alt="image" src="https://user-images.githubusercontent.com/46494851/192806782-cd832930-1c63-4f73-bcce-905af62a8699.png">

Unable to export/import from pgadmin

cc @brettpalmberg

related: https://www.pgadmin.org/docs/pgadmin4/6.9/import_export_servers.html

**Comment by brettpalmberg** [comment]
> Transfer over the "subscribed" USGS sites for certain watersheds.
> 
> Data acquisition has been occurring in develop based on scripted "subscriptions" for a while. This needs to be transferred to stable, but it's complicated to replay those actions.
> 
> Suggestion emptying the following tables in Stable and manually exporting/importing data from Develop:
> 
> 1. usgs_site
> 2. usgs_site_parameters
> 3. watershed_usgs_sites
> 
> This will allow airflow to start acquisition and enable the `extract` endpoints for Stable.
> 
> ❓ Should I also copy over usgs_measurements or just start from now with airflow?
> 
> cc @brettpalmberg

Recommend we forego copying over the measurements and start collecting from present forward.

**Comment by brettpalmberg** [comment]
> 

Any idea what's causing this?

**Comment by adamscarberry** [comment]
This task no longer applies as we no longer connect site parameters to watersheds.  Recommend we close this issue.

**Comment by brettpalmberg** [comment]
> This task no longer applies as we no longer connect site parameters to watersheds. Recommend we close this issue.

Confirmed
