### ISSUE TITLE
Modify visualizations/ Payload

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/water#47]
## Modification to `GET /visualizations/:slug`:

Request to add the following keys to each mapping object in the value for key `mappings:[...]` in the return payload.

- datasource_type (e.g. "cwms-timeseries")
- provider (e.g. "mvp")

I believe `provider` and `datasource_type` are required (in addition to `key` already in payload) to uniquely identify a particular timeseries.

## Modification to `POST /visualizations/:slug/assign`:

Require `provider` (e.g. "mvp") in payload in addition to `variable`, `key`, `datasource_type`. I believe `provider` is needed to ensure arriving at a single timeseries, as different providers could technically make use of identical timeseries keys.

**Comment by brettpalmberg** [comment]
Hey @adamscarberry, are you able to pick this one up?

**Comment by adamscarberry** [comment]
Yep, working on it now.
