### ISSUE TITLE
Remove Schema Name Prefix from Queries

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/water#49]
Recommend removing `a2w_cwms.` prefix from table names. With how the design has evolved, the default search path should be sufficient to ensure the correct tables are queried. Removing the prefix allows flexibility to switch schemas using the search path in the future, without having to modify SQL in models.

**Comment by brettpalmberg** [comment]
@jeffsuperglide or @adamscarberry, would you be able to pick this one up?

**Comment by adamscarberry** [comment]
I'll fix it.
