### ISSUE TITLE
[API]: Datasources GET endpoint (/datasources)

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/water#57]
Create a GET endpoint for datasources. The endpoint will look like this with optional query parameters `datasource_type` and `provider`.

`GET /datasources?datasource_type=cwms-location&provider=lrn`

Example return payload:

`[{ "provider": "lrn", "provider_name": "Nashville District", "datasource_type": "cwms-location", "uri": "https://cwms-data.usace.army.mil/cwms-data/location"}]`

This endpoint will then be used in Airflow DAGs for data syncing. For example, an airflow DAG to sync CWMS locations will have all the information it needs for data retrieval from a third party system by calling the `GET /datasources?datasource_type=cwms-location` endpoint.

Additional background information on the datasource model can be found here: https://develop-water-docs.corps.cloud/#/models/provider .  Additions to the documentation are welcome and encouraged where there are gaps or opportunities for improvement.

**Comment by jeffsuperglide** [comment]
Added branch https://github.com/USACE/water-api/feature/v2-datasource-location with datasource endpoint.

**Comment by brettpalmberg** [comment]
@jeffsuperglide, thanks! Will review this today.

**Comment by jeffsuperglide** [comment]
If the resulting payload is correct, no matter accepted or needs refactored, I'll use that payload to work on the a2w sync locations DAG.

**Comment by brettpalmberg** [comment]
Hey @jeffsuperglide, that makes sense. A slight change-up in the key/value names based on some table name changes to shorten names up.  Here's the final:

Request URL: {{base_url}}/datasources?datatype=cwms-location&provider=lrn

(note query parameter was previously `datasource_type`, now `datatype`).

The response payload looks like this:

```
[
    {
        "provider": "lrn",
        "provider_name": "Nashville District",
        "datatype": "cwms-location",
        "datatype_name": "CWMS Location",
        "datatype_uri": "https://cwms-data.usace.army.mil/cwms-data/location"
    }
]
```

cc @adamscarberry. (Table name change. .sql, seed data, queries, and regression test changes in the latest commit: https://github.com/USACE/water-api/commit/7e2146bcc9c6460507ff111740a64d54df762759).

**Comment by brettpalmberg** [comment]
Work complete and functional tests passing in Postman. Closing at this time. Thanks!
