### ISSUE TITLE
[Airflow]: Refactor DAGs to Use New API Endpoints

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/water#60]
#### Levels

- [ ] ~~a2w_sync_level_paths @adamscarberry~~
  - ~~Use API Endpoint `GET /datasources?datatype=cwms-level`~~

- [ ] ~~a2w_sync_level_values @adamscarberry~~
  - ~~Adjust dynamic DAG approach~~

- [x] a2w_sync_cwms_levels replaces those above @jeffsuperglide 
  - Creates/Updates levels

#### Locations

- [x] a2w_sync_locations @jeffsuperglide
  - `/sync` endpoint eliminated from API. Switch to separate call to POST and PUT endpoints.

~~#### CWMS Timeseries~~

**This feature has been broken-out into a separate issue: #70** 

~~- [ ] a2w_sync_timeseries_paths @jeffsuperglide~~
~~- [ ] aws_sync_timeseries_measurements @adamscarberry~~

~~#### USGS Timeseries~~

~~- [ ] a2w_sync_usgs_measurements~~
~~- [x] a2w_sync_usgs_site_parameters @adamscarberry (will rename to a2w_sync_usgs_timeseries.py)~~
~~- [ ] a2w_sync_usgs_sites @jeffsuperglide~~

**USGS Timeseries DAGs broken-out to separate issue #71**

~~### Priority 2~~
~~- [ ] a2w_sync_nws_locations~~
~~- [ ] a2w_sync_nws_stages~~

**Broken-out into separate issue: #72** 

Additional Updates:

- [ ] Consider RADAR "Hello" Task

- [ ] Add reasonable `execution_timeout` parameter to each `a2w_*` DAG

**Comment by brettpalmberg** [comment]
Related to #57

**Comment by adamscarberry** [comment]
sync_level_paths is mostly done.  Could use some testing.  https://github.com/USACE/airflow-config/pull/203

**Comment by brettpalmberg** [comment]
> a2w_sync_locations

@jeffsuperglide's refactor is complete. Available in branch https://github.com/USACE/airflow-config/tree/feature/a2w-locations-refactor

**Comment by brettpalmberg** [comment]
> Levels

Work in progress is here:

https://github.com/USACE/airflow-config/tree/refactor/sync-levels-v2

@adamscarberry, @jeffsuperglide, can you take a look at this and see if this is complete?

**Comment by jeffsuperglide** [comment]
> > a2w_sync_locations
> 
> @jeffsuperglide's refactor is complete. Available in branch https://github.com/USACE/airflow-config/tree/feature/a2w-locations-refactor

Found an issue in the sync locations while working on sync levels.  Will push an update when I get the sync_locations branch fixed.

**Comment by adamscarberry** [comment]
Update of `a2w_sync_timeseries_measurements` in https://github.com/USACE/airflow-config/pull/204/files

Testing was quick, so it may not be 100% yet.  Still the above PR can be merged when ready.

**Comment by adamscarberry** [comment]
@jeffsuperglide `a2w_sync_cwms_levels` is taking just over a day to run.

![image](https://user-images.githubusercontent.com/46494851/205668500-0a57f3f0-4835-4ca4-80c6-fb1443ce65ff.png)

**Comment by brettpalmberg** [comment]
> 

Let's turn this DAG off in develop until we can do further debug / optimization.

**Comment by brettpalmberg** [comment]
Closing; This list has been broken-out into separate issues #70, #71, #72, #73
