### ISSUE TITLE
[API]: Add location_id FK to timeseries table

### ISSUE THREAD

**Issue by adamscarberry** [USACE/water#63]
- [x] add to sql migration
- [x] fix API to accept location `slug`
- [x] fix regression tests to include `slug`

**Comment by adamscarberry** [comment]
included here: https://github.com/USACE/water-api/pull/111/commits/4fe4d2e0546d740dfce841d5ed1e612526893f92

**Comment by brettpalmberg** [comment]
Complete. Thanks @adamscarberry, closing issue now.
