### ISSUE TITLE
[Airflow]: CWMS Timeseries and Measurements

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/water#70]
Broken-out from previous Github Issue #60.  USACE/water-api endpoints were recently refactored. 

This issue covers implementation of 2 airflow DAGs. 

- [x] etl cwms timeseries paths (without values)
- [x] etl timeseries values for timeseries where values are "enabled" (`"etl_values_enabled": true`) and `"datatype": "cwms-timeseries"`

**Comment by adamscarberry** [comment]
This one should be done. Thanks to @jeffsuperglide for handling the `cwms timeseries paths`
